### ISSUE TITLE
Game Crash!

### ISSUE THREAD

**Issue by Rohzek** [Rohzek/SimpleOreGeneration#29]
Yo, the game crashed with: 
java.lang.NoSuchFieldError: aggroRangePigmen
	at com.gmail.rohzek.blocks.NetherOreBlock.<init>(NetherOreBlock.java:54)
	at com.gmail.rohzek.blocks.SGOres.<clinit>(SGOres.java:56)
	at com.gmail.rohzek.blocks.SGOres$RegistrationHandler.registerBlocks(SGOres.java:244)

Full crash log: https://pastebin.com/Ggh3j71f

**Comment by Rohzek** [comment]
I don't know what caused it. It seemed that the mod wasn't generating it's config file, but then it was trying to read it?
